# version: '3.7'
# services:
#     postgres:
#         container_name: postgres
#         image: postgres:14.1-alpine
#         restart: always
#         environment:
#           POSTGRES_USER: postgres
#           POSTGRES_PASSWORD: postgres
#           POSTGRES_DB: bookings
#           PGDATA: /var/lib/pg_data
#         logging:
#           options:
#             max-size: 10m
#             max-file: "3"
#         ports:
#           - '5432:5432'
#         volumes:
#           - ./pgsqldata://var/lib/pg_data:Z

version: '3.7'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
