version: "3.8"
services:
  postgres:
    container_name: postgres
    image: postgres:14.5-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=reservation
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
  prisma:
    container_name: database-seeder
    command: sh -c "npx prisma migrate dev  && node prisma/seed.js --experimental-fetch"

    ports:
      - 8080:8080
    depends_on:
      - postgres
    image: database-seeder
    build:
      context: .
      dockerfile: Dockerfile-seeder

  # PostgreSQL pgAdmin panel accessible at http://localhost:16543/
  .pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "postgres@postgres.com"
      PGADMIN_DEFAULT_PASSWORD: "postgresadmin!"
    ports:
      - "16543:80"
    depends_on:
      - db

volumes:
  node_modules_cache:
  db:
    driver: local
