version: "3.8"
services:
  postgres:
    container_name: postgres
    image: postgres:14.5-alpine
    restart: always
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
    env_file:
      - .env.test      
  prisma:
    container_name: database-seeder
    command: sh -c "npx dotenv-cli -e .env.test -- npx prisma generate && npx dotenv-cli -e .env.test -- npx prisma migrate deploy  && node --loader ts-node/esm --experimental-specifier-resolution=node prisma/seed.ts"
    ports:
      - 8080:8080
    depends_on:
      - postgres
    image: database-seeder
    build:
      context: .
      dockerfile: docker/Dockerfile-seeder
    volumes:
      - ../reservation-frontend/public/images:/usr/src/app/src/db/seed/images
    env_file:
      - .env.test

  # PostgreSQL pgAdmin panel accessible at http://localhost:16543/
  pgadmin-compose:
    container_name: postgres-admin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "postgres@postgres.com"
      PGADMIN_DEFAULT_PASSWORD: "postgresadmin!"
      GUNICORN_ACCESS_LOGFILE: "/dev/null"
    ports:
      - "16543:80"
    depends_on:
      - db
    volumes:
      - pgadmin:/var/lib/pgadmin
    logging:
      driver: none

volumes:
  node_modules_cache:
  db:
    driver: local
  pgadmin:
    driver: local
